### ISSUE TITLE
TDOA by correlation

### ISSUE THREAD

**Issue by mittal-pooja** [Abhicoder1999/TDOA-Hydrophones#1]
Hi, can you explain how did you found out time delay using correlation, I could not understand it in the code provided.

Thanks!

**Comment by Abhicoder1999** [comment]
hello, I used the frequency domain property of correlation ie. multiplication of X1(f) & conj(X2(f)), where x1 & x2 are the signals. Then I took ifft to get the time-domain correlation result. The result is the same for correlation in the time domain. The position of the peak in the correlation provides information regarding the delay between these two signals. I hope it clears your doubt :)

**Comment by mittal-pooja** [comment]
> hello, I used the frequency domain property of correlation ie. multiplication of X1(f) & conj(X2(f)), where x1 & x2 are the signals. Then I took ifft to get the time-domain correlation result. The result is the same for correlation in the time domain. The position of the peak in the correlation provides information regarding the delay between these two signals. I hope it clears your doubt :)

Hi,  thank you for clearing this out! Another question : how did you correlate two time series?

**Comment by Abhicoder1999** [comment]
Steps:
1. Took a data sequence of the time-series input
2. Converted this time-sequenced input to freq domain using fft
3. did the algorithm as mentioned above related to frequency domain property of correlation.
for more detail check: "https://dsp.stackexchange.com/questions/22877/intuitive-explanation-of-cross-correlation-in-frequency-domain"
4. did ifft to get the final time-domain correlation.

I hope it clears your doubt :)

**Comment by mittal-pooja** [comment]
Hi, Thanks for your reply. I'll try to implement the following, if at all I get stuck somewhere, hopefully I can get back to you!
